# .cargo/release.toml
sign-commit = true
sign-tag = true
dev-version = true
dev-version-ext = "dev"
pre-release-commit-message = "chore: Release version {{version}}"
post-release-commit-message = "chore: Start next development iteration {{next_version}}"
tag-message = "Release version {{version}}"
tag-name = "v{{version}}"
