# .github/workflows/publish.yml
name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Get version
        id: version
        run: echo "version=$(cargo pkgid | cut -d# -f2)" >> $GITHUB_OUTPUT

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update dev branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout dev
          git merge main
          cargo release replace --version $(cargo pkgid | cut -d# -f2)-dev
          git commit -am "chore: Start next development iteration"
          git push origin dev